---

substitutions:
  device_name: "living_room_candle_right"
  friendly_name: "Living Room Candle Right"
  fallback_ap: "Candle Right Fallback Hotspot"
  ip_address: !secret candle_right_ip
  mqtt_broker: !secret mqtt_ip
  mqtt_user: !secret mqtt_user
  mqtt_pass: !secret mqtt_pass

esphome:
  name: $device_name
  platform: ESP32
  board: esp32dev
  on_boot:
    priority: 600
    then:
      - light.turn_on: candle_light

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ip_address
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0
  ap:
    ssid: $fallback_ap
    password: !secret ap_password

mqtt:
  id: mqtt_cli
  broker: $mqtt_broker
  username: $mqtt_user
  password: $mqtt_pass

web_server:
  port: 80

#logger:

ota:
  - platform: esphome
    password: !secret ota_password

#status_led:
#  pin: GPIO22

output:
  - id: candle_output
    platform: gpio
    pin: GPIO32

light:
  - platform: binary
    name: $friendly_name
    id: candle_light
    output: candle_output
