---

esphome:
  project:
    name: "kingmercian.server-power-control"
    version: "1.0.0"
  name: server-power
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 5min
  manual_ip:
    static_ip: !secret server_power_ip
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0
  ap:
    ssid: "PC Power Fallback Hotspot"
    password: !secret ap_password

ota:
  - platform: esphome
    password: !secret ota_password

api:

logger:

web_server:
  port: 80

switch:
  - platform: gpio
    id: power_short_press
    name: "PC Power Toggle"
    icon: "mdi:electric-switch"
    pin:
      number: GPIO21   # Power button output pin
      inverted: false
      allow_other_uses: true
      mode:
        output: true
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: power_short_press
  - platform: gpio
    id: power_long_press
    name: "PC Force Shutdown"
    icon: "mdi:electric-switch"
    pin:
      number: GPIO21   # Power button output pin
      inverted: false
      allow_other_uses: true
      mode:
        output: true
    on_turn_on:
    - delay: 3500ms
    - switch.turn_off: power_long_press

binary_sensor:
  - platform: gpio
    name: "PC Power State"
    device_class: power
    pin:
      number: GPIO22   # Power detect input pin (readback from Reset button)
      inverted: false
      mode:
        input: true
